### ISSUE TITLE
about fft normalization

### ISSUE THREAD

**Issue by zhaozhaoooo** [fltwr/generative-image-dynamics#2]
for every freq, there is four cofficient: the real and imaginary parts of the x-axis, as well as the real and imaginary parts of the y-axis. so for every freq, do you need to compute four deviation and standard deviation?

**Comment by fltwr** [comment]
I use one standard deviation for each frequency.

**Comment by zhaozhaoooo** [comment]
oh! i have seen your code and find that you use one deviation for all frequencys and one standard deviation for every frequency. this method is more simple than that paper but result is relatively great! thanks for your code!
